import { projectMeta, roleStacks, skillItems } from "./shared";
import type { Content } from "./types";

export const en: Content = {
  locale: "en",
  htmlLang: "en",
  ogLocale: "en_US",
  profile: {
    role: "Senior Frontend Engineer",
    tagline: "React · TypeScript · Next.js · AI-assisted development",
    location: "São Paulo, Brazil",
    workModes: "Remote · Hybrid",
    cv: "/resume-renan-augusto.pdf",
    status: "Open to roles and projects",
    pitch:
      "Senior Frontend Engineer with 6+ years shipping web products with React, Next.js and TypeScript — from enterprise dashboards to 3D experiences. I use AI in my daily engineering workflow to ship faster without cutting corners.",
    summary:
      "Senior Frontend Engineer with 6+ years building modern, scalable, high-performance web applications in the React, TypeScript and Next.js ecosystem. I bring Artificial Intelligence into the development lifecycle — Claude Code, Gemini, Copilot and Prompt Engineering — to speed up delivery and raise product quality, backed by solid experience in architecture, UI/UX, Cloud and CI/CD.",
    heroLead:
      "**6+ years** building web products with **React**, **Next.js** and **TypeScript** — from enterprise systems to 3D experiences, with AI in the development workflow.",
  },
  stats: [
    { value: 6, suffix: "+", label: "years in frontend" },
    { value: 60, suffix: "+", label: "public repositories" },
    { value: 70, suffix: "+", label: "certifications" },
  ],
  strengths: [
    { title: "Senior, end to end", text: "From stack and architecture decisions to cloud deployment — I've been the sole frontend engineer on a product." },
    { title: "AI in the engineering workflow", text: "Claude Code, Gemini and Copilot every day; currently pursuing a postgraduate degree in AI and Data Science." },
    { title: "Product and UX", text: "Accessible, responsive interfaces, legacy modernization and data-driven dashboards." },
  ],
  experience: [
    {
      id: "mwm",
      company: "MWM Motores e Geradores",
      title: "Senior Frontend Engineer",
      level: "senior",
      period: "Sep 2025 — Sep 2026",
      place: "São Paulo · Hybrid",
      summary: "Frontend for enterprise and logistics systems, from components to Azure infrastructure.",
      points: [
        "Built SPAs and PWAs with React, TypeScript and Vite for MWM Portal and Bio Plantas.",
        "Delivered logistics and quality dashboards (Google Charts) that centralized gate control, cooperative members and operational data.",
        "Modernized legacy interfaces with Tailwind CSS and Shadcn/UI, improving responsiveness and accessibility.",
        "Automated build and deployment with Docker, Azure Container Apps, ACR and Azure DevOps pipelines.",
        "Integrated the frontend with Java Spring Boot REST APIs and configured Nginx servers.",
      ],
      stack: roleStacks.mwm,
    },
    {
      id: "portal-telemedicina",
      company: "Portal Telemedicina",
      title: "Senior Frontend Engineer",
      level: "senior",
      period: "Oct 2024 — Jan 2025",
      place: "Barueri, Brazil · Remote",
      summary: "Interfaces for a telemedicine platform built with Angular.",
      points: [
        "Developed responsive, accessible interfaces with Angular and TypeScript.",
        "Turned designs into clean code, applying UI/UX principles and testing for robustness.",
        "Integrated APIs and services with continuous delivery through GitHub Actions.",
      ],
      stack: roleStacks["portal-telemedicina"],
    },
    {
      id: "olos",
      company: "Olos Tecnologia",
      title: "Mid-level Frontend Engineer",
      level: "mid",
      period: "Oct 2023 — Jun 2024",
      place: "São Paulo, Brazil",
      summary: "Web products with React and Next.js, focused on UI/UX.",
      points: [
        "Built interfaces with React, Next.js, TypeScript, Styled Components and Material UI.",
        "Implemented responsive layouts following UI/UX best practices.",
        "Maintained CI/CD pipelines on GitHub Actions for continuous, secure delivery.",
      ],
      stack: roleStacks.olos,
    },
    {
      id: "safira",
      company: "SAFIRA Soluções & Tecnologia",
      title: "Mid-level Frontend Engineer",
      level: "mid",
      period: "Mar 2022 — Sep 2023",
      place: "São Paulo · Hybrid",
      summary: "Sole frontend engineer on the product — owner of the stack and the architecture.",
      points: [
        "Defined the stack and designed the frontend architecture end to end.",
        "Created a reusable React/TypeScript component library, JWT authentication and REST integrations.",
        "Made technical calls on performance, scalability and security, and mentored junior developers.",
        "Worked with AWS/Azure cloud and CI/CD pipelines.",
      ],
      stack: roleStacks.safira,
    },
    {
      id: "clude",
      company: "Clude — Cartão de Saúde 360°",
      title: "Frontend Developer Analyst",
      level: "analyst",
      period: "Feb 2020 — Mar 2022",
      place: "São Paulo, Brazil",
      summary: "Where it started: healthcare web applications with React.",
      points: [
        "Built responsive web applications with React.js, JavaScript, Sass and Bootstrap.",
        "Delivered solutions focused on usability and user experience.",
      ],
      stack: roleStacks.clude,
    },
  ],
  projects: [
    {
      ...projectMeta.mwm,
      kind: "Enterprise product · Industry",
      headline: "BI for agro-industrial operations, from data to decision.",
      description:
        "Business Intelligence portal for fueling, billing, collection and cooperative members, with role- and branch-based access control. UI migrated from Bulma to Tailwind + Shadcn/UI.",
    },
    {
      ...projectMeta.aster,
      kind: "Client · Company website",
      headline: "A digital presence that feels welcoming and drives contact.",
      description:
        "Full website for a clinic: responsive landing page with light/dark theme, shareable blog, WhatsApp and form contact, LGPD (privacy) consent and SEO with sitemap and Open Graph.",
    },
    {
      ...projectMeta.escudo,
      kind: "Cybersecurity · Full-stack",
      headline: "Protection against online fraud for everyday people.",
      description:
        "B2C app with a security score dashboard, link checking and monitoring, powered by a dedicated Node.js threat-intelligence API.",
    },
    {
      ...projectMeta.manor,
      kind: "Web game · 3D",
      headline: "A browser escape room with a 3D safe.",
      description:
        "Four chained puzzles and an interactive 3D safe. Flow modeled with XState, state in Zustand, Clean Architecture and E2E tests with Playwright.",
    },
    {
      ...projectMeta.gemini,
      kind: "AI · RAG · Agents",
      headline: "Chat, document analysis and agents in one place.",
      description:
        "Multi-purpose AI system: chat with memory via Google Gemini, document analysis with RAG and semantic search, and autonomous agents orchestrated with LangGraph.",
    },
    {
      ...projectMeta.helios,
      kind: "Game · Physics simulation",
      headline: "Puzzles that are real physical systems.",
      description:
        "Fixed-camera survival horror with a chaotic double pendulum (RK4), Rayleigh convection and a Galton board. Custom renderer and procedural audio.",
    },
    {
      ...projectMeta.gascontrol,
      kind: "Dashboard · Residential buildings",
      headline: "Gas consumption under control.",
      description: "KPIs, consumption charts, alerts, smart sidebar and light/dark theme.",
    },
    {
      ...projectMeta.nexus,
      kind: "3D experience",
      headline: "A Matrix-themed 3D portfolio.",
      description: "GLSL shaders, a sci-fi model and digital rain in React Three Fiber.",
    },
    {
      ...projectMeta.paroquia,
      kind: "Mobile app",
      headline: "Parish communication in your pocket.",
      description: "Mass schedules, daily liturgy, news board, prayer requests and PIX donations, with offline cache.",
    },
  ],
  services: [
    {
      title: "Websites & landing pages",
      text: "Fast, responsive and search-ready — designed to turn visitors into leads.",
      tags: ["Next.js", "SEO", "Animation"],
      example: "Aster Centro Terapêutico",
    },
    {
      title: "Web systems & dashboards",
      text: "Portals and dashboards that organize data and operations, with access control and great usability.",
      tags: ["React", "TypeScript", "Charts"],
      example: "MWM Portal · GasControl",
    },
    {
      title: "3D & interactive experiences",
      text: "Memorable products: WebGL, shaders and interactions that make your brand stick.",
      tags: ["three.js", "WebGL", "GLSL"],
      example: "Manor Escape · this site",
    },
    {
      title: "AI-powered products",
      text: "Chat, document analysis and agents built into your product, with a clear interface.",
      tags: ["Gemini", "RAG", "Agents"],
      example: "Gemini Beyond Prompts",
    },
  ],
  workflow: [
    { step: "01", title: "Discovery", text: "I learn the goal, the audience and what success looks like." },
    { step: "02", title: "Prototype", text: "Structure and visuals validated before writing code." },
    { step: "03", title: "Build", text: "Frequent deliveries with typed, tested code." },
    { step: "04", title: "Launch", text: "Deployment, SEO and follow-up to keep improving with data." },
  ],
  skills: [
    { group: "Frontend", items: skillItems.frontend },
    { group: "UI / UX", items: ["Tailwind CSS", "Shadcn/UI", "Styled Components", "Material UI", "Accessibility", "Figma", "three.js"] },
    { group: "AI & Productivity", items: skillItems.ai },
    { group: "DevOps & Cloud", items: skillItems.devops },
  ],
  education: [
    { title: "Postgraduate degree in Artificial Intelligence and Data Science", org: "Universidade São Judas Tadeu", period: "2026 — present" },
    { title: "Systems Analysis and Development", org: "Universidade São Judas Tadeu", period: "Degree" },
    { title: "Human-Computer Interaction and UX", org: "Universidade São Judas Tadeu", period: "Certification · 2026" },
    { title: "Accessibility with React", org: "Rocketseat", period: "Certification · 2025" },
  ],
  ui: {
    meta: { keywords: ["Senior Frontend Engineer", "React", "Next.js", "TypeScript", "three.js", "Renan Augusto", "portfolio", "Brazil"] },
    skipLink: "Skip to content",
    boot: ["booting renan.dev", "compiling GLSL shaders", "assembling experience"],
    nav: {
      links: [
        { href: "#sobre", label: "Summary", n: "01" },
        { href: "#experiencia", label: "Experience", n: "02" },
        { href: "#projetos", label: "Projects", n: "03" },
        { href: "#servicos", label: "Services", n: "04" },
        { href: "#stack", label: "Stack", n: "05" },
      ],
      hire: "Hire me",
      openMenu: "Open menu",
      closeMenu: "Close menu",
      language: "Language",
    },
    hero: { downloadCv: "Download resume", project: "I have a project", scroll: "SCROLL", hud: "23°33′S 46°38′W · SÃO PAULO" },
    about: { label: "Summary", title: "Senior frontend with a {product mindset}" },
    career: {
      label: "Experience",
      title: "From Analyst to {Senior} in six years",
      sub: "Steady growth on real products — healthcare, telecom, industry and logistics.",
      levels: { analyst: "Analyst", mid: "Mid-level", senior: "Senior" },
      levelTag: "LEVEL",
      since: "since",
      companies: "Companies",
      education: "Education & certifications",
      certifications: "70+ certifications in Frontend, Cloud and AI",
    },
    projects: {
      label: "Projects",
      title: "Real products, {live}",
      sub: "Enterprise systems, client websites, AI products and 3D experiences — click a screen to open each project.",
      proprietary: "Proprietary code",
      live: "View live",
      code: "Code",
      more: "More projects & lab",
      repos: "60+ repositories on GitHub",
      open: "Open",
      screenshotOf: "Screenshot of",
      internalHost: "internal.portal",
      dashboardKpis: ["Fueling", "Billing", "Collection"],
    },
    services: {
      label: "For companies & clients",
      title: "Got a project? {Let's build it.}",
      sub: "From a website that brings in leads to a system that runs your operation — with the same quality bar I bring to enterprise products.",
      example: "E.g.:",
      howIWork: "How I work",
      ctaTitle: "Let's talk about your project?",
      ctaText: "Tell me what you need — I'll reply with the next steps.",
      ctaButton: "Request a quote",
      budgetSubject: "Project quote",
      budgetBody: "Hi Renan,\n\nAbout the project:\n- What needs to be built:\n- Desired timeline:\n- References (links):\n",
    },
    stack: {
      label: "Stack & skills",
      title: "Tools I {master}",
      sub: "From pixel to pipeline: interface, experience, AI-assisted development and the infrastructure that ships it all.",
      rows: [
        ["React", "Next.js", "TypeScript", "three.js", "Tailwind", "Shadcn/UI", "Vite", "GLSL"],
        ["Claude Code", "Gemini", "Copilot", "Docker", "Azure", "CI/CD", "Accessibility", "UI/UX"],
      ],
    },
    contact: {
      label: "Open connection",
      title: "Let's build something {extraordinary?}",
      recruiters: {
        tag: "Recruiters",
        title: "Hiring?",
        text: "Senior Frontend roles with React, Next.js and TypeScript. Up-to-date resume, one click away.",
        primary: "Download resume",
        secondary: "Talk about the role",
        subject: "Opportunity — Senior Frontend",
      },
      clients: {
        tag: "Companies & clients",
        title: "Got a project?",
        text: "Websites, systems, dashboards, AI products and 3D experiences. Share the idea and the timeline.",
        primary: "Request a quote",
        secondary: "See services",
      },
      footer: "Next.js · TypeScript · three.js · made in São Paulo",
      backToTop: "back to top ↑",
    },
  },
};
