import { projectMeta, roleStacks, skillItems } from "./shared";
import type { Content } from "./types";

export const pt: Content = {
  locale: "pt",
  htmlLang: "pt-BR",
  ogLocale: "pt_BR",
  profile: {
    role: "Senior Frontend Engineer",
    tagline: "React · TypeScript · Next.js · IA aplicada ao desenvolvimento",
    location: "São Paulo, Brasil",
    workModes: "Remoto · Híbrido",
    cv: "/curriculo-renan-augusto.pdf",
    status: "Disponível para vagas e projetos",
    pitch:
      "Senior Frontend Engineer com 6+ anos entregando produtos web em React, Next.js e TypeScript — de dashboards corporativos a experiências 3D. Uso IA no dia a dia de engenharia para entregar mais rápido, com qualidade.",
    summary:
      "Senior Frontend Engineer com mais de 6 anos construindo aplicações web modernas, escaláveis e de alta performance no ecossistema React, TypeScript e Next.js. Integro Inteligência Artificial ao ciclo de desenvolvimento — Claude Code, Gemini, Copilot e Prompt Engineering — para acelerar entregas e elevar a qualidade do produto, com base sólida em arquitetura, UI/UX, Cloud e CI/CD.",
    heroLead:
      "**6+ anos** criando produtos web com **React**, **Next.js** e **TypeScript** — de sistemas corporativos a experiências 3D, com IA no fluxo de desenvolvimento.",
  },
  stats: [
    { value: 6, suffix: "+", label: "anos em frontend" },
    { value: 60, suffix: "+", label: "repositórios públicos" },
    { value: 70, suffix: "+", label: "certificações" },
  ],
  strengths: [
    { title: "Sênior de ponta a ponta", text: "Da definição de stack e arquitetura ao deploy em nuvem — já atuei como único frontend de um produto." },
    { title: "IA no fluxo de engenharia", text: "Claude Code, Gemini e Copilot no dia a dia; pós-graduação em IA e Ciência de Dados em andamento." },
    { title: "Produto e UX", text: "Interfaces acessíveis e responsivas, modernização de legado e dashboards orientados a dados." },
  ],
  experience: [
    {
      id: "mwm",
      company: "MWM Motores e Geradores",
      title: "Senior Frontend Engineer",
      level: "senior",
      period: "set/2025 — set/2026",
      place: "São Paulo · Híbrido",
      summary: "Frontend de sistemas corporativos e logísticos, do componente à infraestrutura no Azure.",
      points: [
        "Construí SPAs e PWAs em React, TypeScript e Vite para o MWM Portal e o Bio Plantas.",
        "Entreguei dashboards de logística e qualidade (Google Charts) que centralizaram a gestão de portaria, cooperados e dados operacionais.",
        "Modernizei interfaces legadas para Tailwind CSS e Shadcn/UI, elevando responsividade e acessibilidade.",
        "Automatizei build e deploy com Docker, Azure Container Apps, ACR e pipelines no Azure DevOps.",
        "Integrei o frontend a APIs REST em Java Spring Boot e configurei servidores Nginx.",
      ],
      stack: roleStacks.mwm,
    },
    {
      id: "portal-telemedicina",
      company: "Portal Telemedicina",
      title: "Frontend Engineer Sênior",
      level: "senior",
      period: "out/2024 — jan/2025",
      place: "Barueri, SP · Remoto",
      summary: "Interfaces para uma plataforma de telemedicina em Angular.",
      points: [
        "Desenvolvi interfaces responsivas e acessíveis com Angular e TypeScript.",
        "Traduzi layouts em código limpo, aplicando princípios de UI/UX e testes para garantir robustez.",
        "Integrei APIs e serviços com entrega contínua via GitHub Actions.",
      ],
      stack: roleStacks["portal-telemedicina"],
    },
    {
      id: "olos",
      company: "Olos Tecnologia",
      title: "Frontend Engineer Pleno",
      level: "mid",
      period: "out/2023 — jun/2024",
      place: "São Paulo, SP",
      summary: "Produtos web em React e Next.js com foco em UI/UX.",
      points: [
        "Desenvolvi interfaces com React, Next.js, TypeScript, Styled Components e Material UI.",
        "Implementei layouts responsivos seguindo boas práticas de UI/UX.",
        "Mantive pipelines de CI/CD no GitHub Actions para entregas contínuas e seguras.",
      ],
      stack: roleStacks.olos,
    },
    {
      id: "safira",
      company: "SAFIRA Soluções & Tecnologia",
      title: "Frontend Engineer Pleno",
      level: "mid",
      period: "mar/2022 — set/2023",
      place: "São Paulo · Híbrido",
      summary: "Único desenvolvedor frontend do produto — dono da stack e da arquitetura.",
      points: [
        "Defini a stack e estruturei a arquitetura frontend de ponta a ponta.",
        "Criei biblioteca de componentes reutilizáveis em React/TypeScript, autenticação JWT e integrações REST.",
        "Tomei decisões técnicas de performance, escalabilidade e segurança e mentorei desenvolvedores juniores.",
        "Atuei com cloud AWS/Azure e esteiras de CI/CD.",
      ],
      stack: roleStacks.safira,
    },
    {
      id: "clude",
      company: "Clude — Cartão de Saúde 360°",
      title: "Analista Desenvolvedor Frontend",
      level: "analyst",
      period: "fev/2020 — mar/2022",
      place: "São Paulo, SP",
      summary: "Onde comecei: aplicações web de saúde em React.",
      points: [
        "Desenvolvi aplicações web responsivas com React.js, JavaScript, Sass e Bootstrap.",
        "Entreguei soluções focadas em usabilidade e experiência do usuário.",
      ],
      stack: roleStacks.clude,
    },
  ],
  projects: [
    {
      ...projectMeta.mwm,
      kind: "Produto corporativo · Indústria",
      headline: "BI para operações agroindustriais, do dado à decisão.",
      description:
        "Portal de Business Intelligence para abastecimento, faturamento, coleta e cooperados, com controle de acesso por perfil e filial. Interface migrada de Bulma para Tailwind + Shadcn/UI.",
    },
    {
      ...projectMeta.aster,
      kind: "Cliente · Site institucional",
      headline: "Presença digital que transmite acolhimento e gera contato.",
      description:
        "Site completo para uma clínica: landing responsiva com tema claro/escuro, blog com compartilhamento, contato via WhatsApp e formulário, consentimento LGPD e SEO com sitemap e Open Graph.",
    },
    {
      ...projectMeta.escudo,
      kind: "Cibersegurança · Fullstack",
      headline: "Proteção contra fraudes digitais para o cidadão comum.",
      description:
        "Aplicação B2C com painel de score de segurança, verificação de links e monitoramento, consumindo uma API Node.js dedicada à inteligência de ameaças.",
    },
    {
      ...projectMeta.manor,
      kind: "Jogo web · 3D",
      headline: "Escape room jogável no navegador, com cofre em 3D.",
      description:
        "Quatro enigmas encadeados e um cofre 3D interativo. Fluxo modelado em XState, estado em Zustand, Clean Architecture e testes E2E com Playwright.",
    },
    {
      ...projectMeta.gemini,
      kind: "IA · RAG · Agentes",
      headline: "Chat, análise de documentos e agentes em um só lugar.",
      description:
        "Sistema de IA multifuncional: chat com memória via Google Gemini, análise de documentos com RAG e busca semântica, e agentes autônomos orquestrados com LangGraph.",
    },
    {
      ...projectMeta.helios,
      kind: "Game · Simulação física",
      headline: "Puzzles que são sistemas físicos reais.",
      description:
        "Survival horror em câmera fixa com pêndulo duplo caótico (RK4), convecção de Rayleigh e placa de Galton. Renderer e áudio procedurais próprios.",
    },
    {
      ...projectMeta.gascontrol,
      kind: "Dashboard · Condomínios",
      headline: "Consumo de gás sob controle.",
      description: "KPIs, gráficos de consumo, alertas, sidebar inteligente e tema claro/escuro.",
    },
    {
      ...projectMeta.nexus,
      kind: "Experiência 3D",
      headline: "Portfólio 3D com tema Matrix.",
      description: "Shaders GLSL, modelo sci-fi e chuva de código em React Three Fiber.",
    },
    {
      ...projectMeta.paroquia,
      kind: "App mobile",
      headline: "Comunicação paroquial no bolso.",
      description: "Horários, liturgia diária, mural, pedidos de oração e dízimo via PIX, com cache offline.",
    },
  ],
  services: [
    {
      title: "Sites e landing pages",
      text: "Rápidos, responsivos e prontos para o Google — pensados para transformar visita em contato.",
      tags: ["Next.js", "SEO", "Animações"],
      example: "Aster Centro Terapêutico",
    },
    {
      title: "Sistemas web e dashboards",
      text: "Painéis e portais que organizam dados e operação, com controle de acesso e ótima usabilidade.",
      tags: ["React", "TypeScript", "Gráficos"],
      example: "MWM Portal · GasControl",
    },
    {
      title: "Experiências 3D e interativas",
      text: "Produtos que marcam: WebGL, shaders e interações que fazem sua marca ser lembrada.",
      tags: ["three.js", "WebGL", "GLSL"],
      example: "Manor Escape · este site",
    },
    {
      title: "Produtos com IA",
      text: "Chat, análise de documentos e agentes integrados ao seu produto, com interface clara.",
      tags: ["Gemini", "RAG", "Agentes"],
      example: "Gemini Beyond Prompts",
    },
  ],
  workflow: [
    { step: "01", title: "Descoberta", text: "Entendo o objetivo, o público e o que define sucesso." },
    { step: "02", title: "Protótipo", text: "Estrutura e visual validados antes de escrever código." },
    { step: "03", title: "Desenvolvimento", text: "Entregas frequentes, com código tipado e testado." },
    { step: "04", title: "Lançamento", text: "Deploy, SEO e acompanhamento para evoluir com dados." },
  ],
  skills: [
    { group: "Frontend", items: skillItems.frontend },
    { group: "UI / UX", items: ["Tailwind CSS", "Shadcn/UI", "Styled Components", "Material UI", "Acessibilidade", "Figma", "three.js"] },
    { group: "IA & Produtividade", items: skillItems.ai },
    { group: "DevOps & Cloud", items: skillItems.devops },
  ],
  education: [
    { title: "Pós-graduação em Inteligência Artificial e Ciência de Dados", org: "Universidade São Judas Tadeu", period: "2026 — atual" },
    { title: "Análise e Desenvolvimento de Sistemas", org: "Universidade São Judas Tadeu", period: "Graduação" },
    { title: "Interação Humano-Computador e UX", org: "Universidade São Judas Tadeu", period: "Certificação · 2026" },
    { title: "Acessibilidade com React", org: "Rocketseat", period: "Certificação · 2025" },
  ],
  ui: {
    meta: { keywords: ["Senior Frontend Engineer", "React", "Next.js", "TypeScript", "three.js", "Renan Augusto", "portfólio", "São Paulo"] },
    skipLink: "Pular para o conteúdo",
    boot: ["iniciando renan.dev", "compilando shaders GLSL", "montando experiência"],
    nav: {
      links: [
        { href: "#sobre", label: "Resumo", n: "01" },
        { href: "#experiencia", label: "Experiência", n: "02" },
        { href: "#projetos", label: "Projetos", n: "03" },
        { href: "#servicos", label: "Serviços", n: "04" },
        { href: "#stack", label: "Stack", n: "05" },
      ],
      hire: "Contratar",
      openMenu: "Abrir menu",
      closeMenu: "Fechar menu",
      language: "Idioma",
    },
    hero: { downloadCv: "Baixar currículo", project: "Tenho um projeto", scroll: "SCROLL", hud: "23°33′S 46°38′W · SÃO PAULO" },
    about: { label: "Resumo", title: "Frontend sênior com {visão de produto}" },
    career: {
      label: "Experiência",
      title: "De Analista a {Sênior} em seis anos",
      sub: "Uma trajetória de crescimento contínuo em produtos reais — saúde, telecom, indústria e logística.",
      levels: { analyst: "Analista", mid: "Pleno", senior: "Sênior" },
      levelTag: "NÍVEL",
      since: "desde",
      companies: "Empresas",
      education: "Formação & certificações",
      certifications: "+70 certificações em Frontend, Cloud e IA",
    },
    projects: {
      label: "Projetos",
      title: "Produtos reais, {no ar}",
      sub: "Sistemas corporativos, sites para clientes, produtos com IA e experiências 3D — clique nas telas para abrir cada projeto.",
      proprietary: "Código proprietário",
      live: "Ver ao vivo",
      code: "Código",
      more: "Mais projetos & laboratório",
      repos: "+60 repositórios no GitHub",
      open: "Abrir",
      screenshotOf: "Tela do projeto",
      internalHost: "portal.interno",
      dashboardKpis: ["Abastecimento", "Faturamento", "Coleta"],
    },
    services: {
      label: "Para empresas & clientes",
      title: "Tem um projeto? {Eu tiro do papel.}",
      sub: "Do site que gera contatos ao sistema que organiza sua operação — com o mesmo padrão de qualidade que uso em produtos corporativos.",
      example: "Ex.:",
      howIWork: "Como trabalho",
      ctaTitle: "Vamos conversar sobre o seu projeto?",
      ctaText: "Conte o que você precisa — respondo com os próximos passos.",
      ctaButton: "Solicitar orçamento",
      budgetSubject: "Orçamento de projeto",
      budgetBody: "Olá, Renan!\n\nSobre o projeto:\n- O que precisa ser feito:\n- Prazo desejado:\n- Referências (links):\n",
    },
    stack: {
      label: "Stack & competências",
      title: "Ferramentas que {domino}",
      sub: "Do pixel ao pipeline: interface, experiência, IA aplicada ao desenvolvimento e a infraestrutura que coloca tudo em produção.",
      rows: [
        ["React", "Next.js", "TypeScript", "three.js", "Tailwind", "Shadcn/UI", "Vite", "GLSL"],
        ["Claude Code", "Gemini", "Copilot", "Docker", "Azure", "CI/CD", "Acessibilidade", "UI/UX"],
      ],
    },
    contact: {
      label: "Conexão aberta",
      title: "Vamos construir algo {extraordinário?}",
      recruiters: {
        tag: "Recrutadores",
        title: "Tem uma vaga?",
        text: "Posições Senior Frontend com React, Next.js e TypeScript. Currículo atualizado a um clique.",
        primary: "Baixar currículo",
        secondary: "Falar sobre a vaga",
        subject: "Oportunidade — Senior Frontend",
      },
      clients: {
        tag: "Empresas & clientes",
        title: "Tem um projeto?",
        text: "Sites, sistemas, dashboards, produtos com IA e experiências 3D. Conte a ideia e o prazo.",
        primary: "Solicitar orçamento",
        secondary: "Ver serviços",
      },
      footer: "Next.js · TypeScript · three.js · feito em São Paulo",
      backToTop: "voltar ao topo ↑",
    },
  },
};
